version: "3.9"

services:

  backend:
    container_name: ApiBaileysMd
    hostname: ApiBaileysMd
    network_mode: bridge
    image: alanmartines/mywhatsapp-api-node-api-baileys-md:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: always
    volumes:
      - .:/home/ApiBaileysMd
      - /usr/local/tokens:/usr/local/tokens
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 9001
      DOMAIN_SSL: ${DOMAIN_SSL:-}
      VIEW_QRCODE_TERMINAL: ${VIEW_QRCODE_TERMINAL:-1}
      DEVICE_NAME: ${DEVICE_NAME:-'My-Whatsapp'}
      WA_VERSION: ${WA_VERSION:-}
      PATCH_TOKENS: ${PATCH_TOKENS:-/usr/local/tokens}
      AUTO_CLOSE: ${AUTO_CLOSE:-10}
      SECRET_KEY: ${SECRET_KEY:-09f26e402586e2faa8da4c98a35f1b20d6b033c60}
      VALIDATE_MYSQL: ${VALIDATE_MYSQL:-0}
      MYSQL_HOST: ${MYSQL_HOST:-mysql}
      MYSQL_PORT: ${MYSQL_PORT:-3306}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-strongpassword}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-mywhatsapp-api}
      MYSQL_DIALECT: ${MYSQL_DIALECT:-mysql}
      MYSQL_TIMEZONE: ${MYSQL_TIMEZONE:-'-04:00'}
      BROWSER_WSENDPOINT: ${BROWSER_WSENDPOINT:-}
      START_ALL_SESSIONS: ${START_ALL_SESSIONS:-0}
      FORCE_CONNECTION_USE_HERE: ${FORCE_CONNECTION_USE_HERE:-0}
    ports:
      - ${PORT:-1000}:9001

#mysql:
#    container_name: ApiDatabase
#    hostname: ApiDatabase
#    #network_mode: bridge
#    image: ${MYSQL_ENGINE:-mariadb}:${MYSQL_VERSION:-10.6}
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin    
#    volumes:
#      - ./.docker/data/:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE:-mywhatsapp-api}
#      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD:-strongpassword}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-strongpassword}
#      TZ: ${TZ:-America/Sao_Paulo}
#    ports:
#      - ${MYSQL_PORT:-3306}:3306
#    restart: always
#    networks:
#      - mywhatsapp-api

# Criar um contêiner
# docker compose -f docker-compose.yml up --build -d