version: "3.9"

services:
  backend:
    image: alanmartines/mywhatsapp-api-node-baileys-md:1.0.0
    env_file: .env
    volumes:
      - .:/home/ApiBaileysMd:rw
      - ${PATCH_TOKENS:-/usr/local/tokensHomologacao}:/usr/local/tokens:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORT:-9001}:9001
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.50"
          memory: 2048M
        reservations:
          cpus: "0.25"
          memory: 1024M
    networks:
      - apiwhatsapp_overlay

networks:
  apiwhatsapp_overlay:
    driver: overlay
