version: "3.9"

services:

  backend:
    container_name: ${HOST_NAME:-'ApiBaileysMd'}
    hostname: ${HOST_NAME:-'ApiBaileysMd'}
    network_mode: bridge
    image: alanmartines/mywhatsapp-api-node-baileys-md:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    env_file: .env
    volumes:
      - .:/home/ApiBaileysMd:rw
      - ${PATCH_TOKENS:-/usr/local/tokensHomologacao}:/usr/local/tokens:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${PORT:-1000}:9001
    expose:
      - ${PORT:-9001}

#    logging:
#      driver: gelf
#      options:
#        gelf-address: "udp://${GRAYLOGSERVER:-127.0.0.1}:${GRAYLOGPORT:-12201}"